website/homepage/urls.py
from django.conf.urls import url
from .import views

urlpatterns=[
    url(r'^$', views.homepage, name="homepage"),
    url(r'^newpost/$',views.newpost,name="newpost"),
    url(r'^(?P<slug>[\w-]+)/$',views.postdetails,name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.editpost, name='editpost'),
]
 

website/users/urls.py
from django.conf.urls import url
from .import views

app_name='users'

urlpatterns=[
    url(r'^signin/$',views.userform,name="signin"),
    url(r'^login/$',views.loginform,name="login"),
    url(r'^logout/$',views.logoutform,name="logout"),
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^homepage/', include('homepage.urls')),
    url(r'^users/',include('users.urls')),
]

urlpatterns+= staticfiles_urlpatterns()

website/homepage/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.title
    def snip(self):
        return self.body[:100]+'---'
    

website/users/models.py
from django.db import models

# Create your models here.

website/homepage/forms.py
from .import models
from django import forms

class writepost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','slug','body']

class EditPost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','slug','body']

website/homepage/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms

def homepage(request):
    posts = Post.objects.all().order_by('date')
    return render(request,'homepage/homepage.html',{'posts': posts})
   
def postdetails(request, slug):
    post=Post.objects.get(slug=slug)
    return render(request,'homepage/postdetails.html',{'post':post})

def editpost(request,slug):
    post = Post.objects.get(slug=slug) 
    if request.method == 'POST':
        form = forms.EditPost(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('http://127.0.0.1:8000/homepage/')
    else:
        form = forms.EditPost(instance=post)
    return render(request, 'homepage/editpost.html', {'form': form})

@login_required(login_url="/users/login/")
def newpost(request):
    if request.method =='POST':
        form = forms.writepost(request.POST,request.FILES)
        if form.is_valid():
            profile= form.save(commit=False)
            profile.writer= request.user
            profile.save()
            return redirect('http://127.0.0.1:8000/homepage/')
    else:
        form = forms.writepost()
    return render(request,'homepage/newpost.html',{'form': form })

website/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def userform(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('http://127.0.0.1:8000/homepage/newpost')
    else:
        form=UserCreationForm()
    return render (request,'users/signin.html', {'form':form})

def loginform(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('http://127.0.0.1:8000/homepage/')
    else:
        form= AuthenticationForm()
    return render(request,'users/login.html',{'form':form})

def logoutform(request):
    if request.method =='POST':
        logout(request)
        return redirect('http://127.0.0.1:8000/homepage/')

website/homepage/templates/homepage/editpost.html
{% extends 'baselayout.html' %}

{% block content %}
<h1>Edit Post {{ article.title }}</h1>
<div class="profile">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</div>
{% endblock %}

website/homepage/templates/homepage/homepage.html
{% extends 'baselayout.html' %}

{% block content %}
    <h1><center>List of Posts</center></h1><br/><br/>
    <div class="posts">
        {% for post in posts %}
         <div class="post">
             <h2><a href="{% url 'detail' slug=post.slug%}">{{post.title}}</a></h2>
             {% if request.user == post.writer %}
               <p><a href="{% url 'editpost' slug=post.slug %}">Edit Post</a></p>
             {% endif %}
             <p>{{ post.snip }}</p>
             <p>{{ post.date }}</p>
         </div>
        {% endfor %}
    </div>
{% endblock %}

website/homepage/templates/homepage/newpost.html
{% extends 'baselayout.html' %}

{% block content %}
 <div class="newpost">
     <h1><center>Write A New Post</center></h1>
     <form class="site-form" action="{% url 'newpost' %}" method="post">
         {% csrf_token %}
         {{ form }}
         <input type="submit" value="Submit">
     </form>
 </div>
{% endblock %}

website/homepage/templates/homepage/postdetails.html
{% extends 'baselayout.html' %}
{% block content %}
<div class="postdetail">
    <div class="post">
        <h2>{{post.title}}</h2>
        <p>{{post.date}}</p>
        <p>{{post.body}}</p>
        <p>{{post.writer}}</p>
    </div>
</div>
{% endblock %}

website/templates/baselayout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        <nav>
            <ul>
                    <form class="loginlink" action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Login</button>
                    </form>
                    <form class="logoutlink" action="{% url 'users:logout' %}" method = "post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                    <form class="signinlink" action="{% url 'users:signin' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">SignUp</button>
                    </form>
                    <form class="writepostlink" action="{% url 'newpost' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">New Post</button>
                    </form>
                    <form class="gohomelink" action="{% url 'homepage' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Homepage</button>
                    </form>
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

website/users/templates/users/login.html
{% extends 'baselayout.html' %}

{% block content %}
  <h1><center>LogIn Form</center></h1>
  <form action="/users/login/" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value="Login">
  </form>
{% endblock %}

website/users/templates/users/signin.html
{% extends 'baselayout.html' %}

{% block content %}
  <h1><center>Sign In Form</center></h1>
  <form action="/users/signin/" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Signup">
  </form>
{% endblock %}